#################
### AUTOSTART ###
#################

#detect GPU and set env vars accordingly
exec-once = ~/.config/hypr/scripts/detect_gpu.sh

# Terminal example (uncomment if you want a terminal at startup)
# exec-once = $terminal

# Network applet
# exec-once = nm-applet &

# Waybar
exec-once = waybar &

# Wallpapers
exec-once = hyprpaper &

# Idle manager (locks screen + DPMS off, no suspend)
exec-once = hypridle &

# Bluetooth manager
exec-once = blueman-applet &

# Waybar updates (weather, system updates)
exec-once = sleep 60 && pkill -RTMIN+2 waybar   # weather
exec-once = sleep 60 && pkill -RTMIN+1 waybar   # updates