#!/usr/bin/env bash

set -euo pipefail

### ========= CONFIG ========= ###
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_DIR="$REPO_DIR/.config"
BACKUP_DIR="$HOME/.config-backup-$(date +%s)"
DRY_RUN=0
GPU_PROFILE="generic_gpu.conf"
VERIFY_ONLY=0

### ========= LOGGING ========= ###
log() { echo -e "\e[1;32m[INFO]\e[0m $1"; }
warn() { echo -e "\e[1;33m[WARN]\e[0m $1"; }
err()  { echo -e "\e[1;31m[ERROR]\e[0m $1"; exit 1; }

usage() {
    cat <<EOF
Usage: $0 [--dry-run|-n]

Options:
  -n, --dry-run   Show actions without making changes
      --verify    Run post-install healthcheck only
  -h, --help      Show this help message
EOF
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -n|--dry-run)
                DRY_RUN=1
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            --verify)
                VERIFY_ONLY=1
                ;;
            *)
                err "Unknown option: $1"
                ;;
        esac
        shift
    done
}

run_cmd() {
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "[dry-run] $*"
    else
        "$@"
    fi
}

### ========= CHECKS ========= ###
require_user() {
    if [[ "$EUID" -eq 0 ]]; then
        err "Do NOT run as root"
    fi
}

verify_setup() {
    log "Running healthcheck..."

    local missing=0
    local cmds=(
        Hyprland
        waybar
        kitty
        hyprpaper
        hypridle
        hyprlock
        jq
        python
        checkupdates
    )

    for cmd in "${cmds[@]}"; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            warn "Missing command: $cmd"
            ((missing+=1))
        fi
    done

    local required_files=(
        "$HOME/.config/hypr/hyprland.conf"
        "$HOME/.config/hypr/env_var/current_gpu.conf"
        "$HOME/.config/waybar/config.jsonc"
        "$HOME/.config/waybar/scripts/kb.sh"
        "$HOME/.config/waybar/scripts/updates.sh"
        "$HOME/.config/waybar/scripts/installupdates.sh"
    )

    for path in "${required_files[@]}"; do
        if [[ ! -e "$path" ]]; then
            warn "Missing file: $path"
            ((missing+=1))
        fi
    done

    if [[ -f "$HOME/.config/hypr/env_var/current_gpu.conf" ]] && ! grep -q '^source = ~/.config/hypr/env_var/gpu/' "$HOME/.config/hypr/env_var/current_gpu.conf"; then
        warn "current_gpu.conf does not source a valid GPU profile"
        ((missing+=1))
    fi

    if [[ "$missing" -eq 0 ]]; then
        log "Healthcheck passed"
        return
    fi

    err "Healthcheck found $missing issue(s)"
}

### ========= GPU DETECTION ========= ###
detect_gpu_profile() {
    local gpu
    gpu="$(lspci | grep -E "VGA|3D" || true)"

    if [[ -z "$gpu" ]]; then
        warn "No compatible GPU detected from lspci output; using generic profile"
        GPU_PROFILE="generic_gpu.conf"
        return
    fi

    if echo "$gpu" | grep -qi "AMD"; then
        GPU_PROFILE="amd.conf"
    elif echo "$gpu" | grep -qi "NVIDIA"; then
        GPU_PROFILE="nvidia.conf"
    elif echo "$gpu" | grep -qi "Intel"; then
        GPU_PROFILE="intel.conf"
    else
        GPU_PROFILE="generic_gpu.conf"
    fi

    log "GPU profile selected: $GPU_PROFILE"
}

install_gpu_drivers() {
    log "Detecting GPU..."
    detect_gpu_profile

    case "$GPU_PROFILE" in
        amd.conf)
            log "AMD GPU detected"
            run_cmd sudo pacman -S --noconfirm \
                mesa vulkan-radeon libva-mesa-driver \
                vulkan-tools mesa-utils
            ;;
        nvidia.conf)
            log "NVIDIA GPU detected"
            run_cmd sudo pacman -S --noconfirm \
                nvidia nvidia-utils nvidia-settings
            ;;
        intel.conf)
            log "Intel GPU detected"
            run_cmd sudo pacman -S --noconfirm \
                mesa vulkan-intel intel-media-driver
            ;;
        *)
            warn "Unknown GPU - skipping vendor-specific drivers"
            ;;
    esac
}

write_current_gpu_profile() {
    local current_gpu_file="$HOME/.config/hypr/env_var/current_gpu.conf"
    local target_profile="$GPU_PROFILE"

    [[ -n "$target_profile" ]] || target_profile="generic_gpu.conf"

    if [[ ! -f "$HOME/.config/hypr/env_var/gpu/$target_profile" ]]; then
        warn "GPU profile file missing for $target_profile, falling back to generic_gpu.conf"
        target_profile="generic_gpu.conf"
    fi

    if [[ "$DRY_RUN" -eq 1 ]]; then
        log "[dry-run] write source = ~/.config/hypr/env_var/gpu/$target_profile to $current_gpu_file"
        return
    fi

    cat > "$current_gpu_file" <<EOF
# Auto-generated by install.sh
source = ~/.config/hypr/env_var/gpu/$target_profile
EOF
    log "Wrote GPU profile source to $current_gpu_file"
}

### ========= CORE ========= ###
install_core() {
    log "Installing core system..."

    run_cmd sudo pacman -Syu --noconfirm

    CORE_PKGS=(
        hyprland
        hyprlauncher
        waybar
        kitty
        greetd

        networkmanager
        bluez
        bluez-utils

        pipewire
        pipewire-alsa
        pipewire-pulse
        wireplumber

        polkit
        polkit-gnome

        xdg-desktop-portal-hyprland
        xdg-user-dirs
        xdg-utils

        wl-clipboard
        grim
        slurp
        hyprpaper
        hypridle
        hyprlock
        jq
        curl
        playerctl
        brightnessctl
        pavucontrol
        blueman
        libnotify
        pacman-contrib
        python
        python-requests

        seatd

        ttf-dejavu
        ttf-font-awesome
        noto-fonts

        git
        base-devel
    )

    for pkg in "${CORE_PKGS[@]}"; do
        if ! pacman -Qi "$pkg" &>/dev/null; then
            log "Installing $pkg"
            run_cmd sudo pacman -S --noconfirm "$pkg"
        fi
    done

    install_gpu_drivers
}

### ========= APPS ========= ###
install_apps() {
    log "Installing optional apps..."

    APP_PKGS=(
        thunderbird
        chromium
        vivaldi
        krusader
        nautilus
        mission-center
        htop
        dunst
        network-manager-applet
    )

    for pkg in "${APP_PKGS[@]}"; do
        if ! pacman -Qi "$pkg" &>/dev/null; then
            log "Installing $pkg"
            run_cmd sudo pacman -S --noconfirm "$pkg" || warn "Failed: $pkg"
        fi
    done
}

### ========= CONFIGS ========= ###
install_configs() {
    log "Installing configs..."

    run_cmd mkdir -p "$HOME/.config"
    run_cmd mkdir -p "$BACKUP_DIR"

    # Install these config directories into ~/.config.
    # Prefer repo/.config/<name>, fallback to repo-root/<name> for compatibility.
    CONFIG_DIRS=(
        hypr
        kitty
        waybar
    )

    for name in "${CONFIG_DIRS[@]}"; do
        if [[ -d "$CONFIG_DIR/$name" ]]; then
            src="$CONFIG_DIR/$name"
        elif [[ -d "$REPO_DIR/$name" ]]; then
            src="$REPO_DIR/$name"
        else
            warn "Missing config dir: $name (checked $CONFIG_DIR and repo root)"
            continue
        fi

        target="$HOME/.config/$name"

        if [[ -e "$target" ]]; then
            warn "Backing up $target"
            run_cmd mv "$target" "$BACKUP_DIR/"
        fi

        run_cmd cp -r "$src" "$target"
        log "Installed $name -> $target"
    done

    # Install dotfiles from repo root into $HOME
    DOTFILES=(
        .bashrc
    )

    for file in "${DOTFILES[@]}"; do
        src="$REPO_DIR/$file"
        target="$HOME/$file"

        [[ -f "$src" ]] || { warn "Missing dotfile: $file (skipping)"; continue; }

        if [[ -e "$target" ]]; then
            warn "Backing up $target"
            run_cmd mv "$target" "$BACKUP_DIR/"
        fi

        run_cmd cp "$src" "$target"
        log "Installed $file -> $target"
    done

    SCRIPT_FILES=(
        "$HOME/.config/hypr/scripts/detect_gpu.sh"
        "$HOME/.config/waybar/scripts/kb.sh"
        "$HOME/.config/waybar/scripts/updates.sh"
        "$HOME/.config/waybar/scripts/installupdates.sh"
    )

    for script in "${SCRIPT_FILES[@]}"; do
        if [[ -f "$script" ]]; then
            run_cmd chmod +x "$script"
            log "Made executable: $script"
        fi
    done

    write_current_gpu_profile
}

### ========= SERVICES ========= ###
enable_services() {
    log "Enabling services..."

    SERVICES=(
        NetworkManager
        bluetooth
        seatd
    )

    for svc in "${SERVICES[@]}"; do
        run_cmd sudo systemctl enable "$svc" --now || warn "Failed to enable or start service: $svc"
    done
}

### ========= GREETD ========= ###
setup_greetd() {
    log "Configuring greetd..."

    run_cmd sudo mkdir -p /etc/greetd

    local greetd_user="$USER"
    if [[ ! "$greetd_user" =~ ^[a-z_][a-z0-9_-]*$ ]]; then
        err "Unsafe username for greetd config: $greetd_user"
    fi

    local hyprland_cmd
    hyprland_cmd="$(command -v Hyprland || true)"
    if [[ -z "$hyprland_cmd" ]]; then
        hyprland_cmd="/usr/bin/Hyprland"
    fi

    local tmp_cfg
    tmp_cfg="$(mktemp)"
    cat > "$tmp_cfg" <<EOF
[terminal]
vt = 1

[default_session]
command = "$hyprland_cmd"
user = "$greetd_user"
EOF

    if [[ "$DRY_RUN" -eq 1 ]]; then
        if [[ -f /etc/greetd/config.toml ]]; then
            run_cmd sudo cp /etc/greetd/config.toml "/etc/greetd/config.toml.bak.$(date +%s)"
            warn "Backed up existing /etc/greetd/config.toml"
        fi
    else
        if sudo test -f /etc/greetd/config.toml; then
            run_cmd sudo cp /etc/greetd/config.toml "/etc/greetd/config.toml.bak.$(date +%s)"
            warn "Backed up existing /etc/greetd/config.toml"
        fi
    fi

    run_cmd sudo install -m 0644 "$tmp_cfg" /etc/greetd/config.toml
    rm -f "$tmp_cfg"
}

### ========= MAIN ========= ###
main() {
    parse_args "$@"

    if [[ "$VERIFY_ONLY" -eq 1 ]]; then
        verify_setup
        exit 0
    fi

    require_user

    log "Starting Devitana Arch setup (official repos only)..."
    [[ "$DRY_RUN" -eq 1 ]] && log "Dry-run mode enabled; no changes will be made"

    install_core
    install_apps
    install_configs
    enable_services
    setup_greetd

    log "Setup complete!"
    log "Reboot recommended."
}

main "$@"
