-- autostart.lua  –  exec-once launch list
-- Generates: hypr/autostart/startup.conf

hl.heading("AUTOSTART")
hl.comment("GPU profile is selected during install and written to env_var/current_gpu.conf")
hl.raw("")
hl.comment("Terminal example (uncomment if you want a terminal at startup)")
hl.raw("# exec-once = $terminal")
hl.raw("")
hl.comment("Network applet")
hl.raw("# exec-once = nm-applet &")
hl.raw("")
hl.comment("Waybar")
hl.keyword("exec-once", "waybar &")
hl.raw("")
hl.comment("Wallpapers")
hl.keyword("exec-once", "hyprpaper &")
hl.raw("")
hl.comment("Idle manager (locks screen + DPMS off, no suspend)")
hl.keyword("exec-once", "hypridle &")
hl.raw("")
hl.comment("Bluetooth manager")
hl.keyword("exec-once", "blueman-applet &")
hl.raw("")
hl.comment("Waybar updates (weather, system updates)")
hl.comment("weather")
hl.keyword("exec-once", "sleep 60 && pkill -RTMIN+2 waybar")
hl.comment("updates")
hl.keyword("exec-once", "sleep 60 && pkill -RTMIN+1 waybar")
