-- gpu_intel.lua
-- Source-of-truth for hypr/env_var/gpu/intel.conf
-- Intel iGPU / Arc Vulkan optimizations. Generated by generate.lua.

return {
  header = "#################################\n### INTEL GPU OPTIMIZATION     ###\n#################################\n",
  comment = "# Intel iGPU and Arc GPU support\n",
  sections = {
    {
      vars = {
        { key = "WLR_RENDERER",            value = "vulkan" },
        { key = "WLR_NO_HARDWARE_CURSORS", value = "1" },
      },
    },
    {
      comment = "# Intel Vulkan driver (choose one based on your GPU)\n# For older Intel iGPU (UHD/Iris):",
      vars = {
        { key = "VK_ICD_FILENAMES", value = "/usr/share/vulkan/icd.d/intel_icd.x86_64.json" },
      },
      -- Newer Arc variant (commented out):
      commented_vars = {
        { key = "VK_ICD_FILENAMES", value = "/usr/share/vulkan/icd.d/intel_hasvk_icd.x86_64.json",
          comment = "For newer Intel Arc GPU:" },
      },
    },
    {
      comment = "# Intel-specific settings",
      vars = {
        { key = "INTEL_PRECISE_TRIG",              value = "1" },
        { key = "MESA_LOADER_DRIVER_OVERRIDE",     value = "iris" },
        { key = "INTEL_DEBUG",                     value = "" },
      },
    },
    {
      comment = "# VRR/Adaptive Sync (may work on newer Arc)",
      vars = {
        { key = "__GL_GSYNC_ALLOWED", value = "1" },
        { key = "__GL_VRR_ALLOWED",   value = "1" },
      },
    },
    {
      comment = "# Present mode",
      vars = {
        { key = "MESA_VK_WSI_PRESENT_MODE", value = "mailbox" },
      },
    },
  },
}
