-- gpu_nvidia.lua
-- Source-of-truth for hypr/env_var/gpu/nvidia.conf
-- NVIDIA Wayland/Vulkan optimizations. Generated by generate.lua.

return {
  header = "#################################\n### NVIDIA OPTIMIZATION        ###\n#################################\n",
  sections = {
    {
      comment = "# Wayland + NVIDIA",
      vars = {
        { key = "__NV_PRIME_RENDER_OFFLOAD",  value = "1" },
        { key = "__GLX_VENDOR_LIBRARY_NAME",  value = "nvidia" },
        { key = "GBM_BACKEND",                value = "nvidia-drm" },
        { key = "__VK_LAYER_NV_optimus",      value = "NVIDIA_only" },
      },
    },
    {
      comment = "# Vulkan ICD for NVIDIA",
      vars = {
        { key = "VK_ICD_FILENAMES", value = "/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json" },
      },
    },
    {
      comment = "# NVIDIA-specific settings",
      vars = {
        { key = "NVIDIA_MIG_CONFIG",       value = "disabled" },
        { key = "NVIDIA_PRESERVE_VIDEOCORE", value = "1" },
      },
    },
    {
      comment = "# VRR/Adaptive Sync (NVIDIA G-Sync)",
      vars = {
        { key = "__GL_GSYNC_ALLOWED", value = "1" },
        { key = "__GL_VRR_ALLOWED",   value = "1" },
      },
    },
    {
      comment = "# Wayland rendering",
      vars = {
        { key = "WLR_RENDERER",             value = "vulkan" },
        { key = "WLR_NO_HARDWARE_CURSORS",  value = "1" },
        { key = "MESA_VK_WSI_PRESENT_MODE", value = "fifo" },
      },
    },
  },
}
