-- gpu_generic.lua
-- Source-of-truth for hypr/env_var/gpu/generic_gpu.conf
-- Generic Wayland / Vulkan settings. Generated by generate.lua.

return {
  header = "#################################\n### GENERIC WAYLAND SETTINGS   ###\n#################################\n",
  sections = {
    {
      comment = "# Generic Vulkan configuration",
      vars = {
        { key = "WLR_RENDERER",            value = "vulkan" },
        { key = "WLR_NO_HARDWARE_CURSORS", value = "1" },
      },
    },
    {
      comment = "# Generic VRR settings",
      vars = {
        { key = "__GL_GSYNC_ALLOWED", value = "1" },
        { key = "__GL_VRR_ALLOWED",   value = "1" },
      },
    },
    {
      comment = "# Default present mode",
      vars = {
        { key = "MESA_VK_WSI_PRESENT_MODE", value = "mailbox" },
      },
    },
  },
}
