-- gpu_amd.lua
-- Source-of-truth for hypr/env_var/gpu/amd.conf
-- AMD / Mesa Vulkan optimizations. Generated by generate.lua.

return {
  header = "###############################\n### AMD / MESA OPTIMIZATION ###\n###############################\n",
  vars = {
    { key = "WLR_RENDERER",              value = "vulkan" },
    { key = "WLR_NO_HARDWARE_CURSORS",   value = "1" },
    { key = "RADV_PERFTEST",             value = "gpl" },
    { key = "AMD_VULKAN_ICD",            value = "radv" },
    { key = "MESA_VK_WSI_PRESENT_MODE",  value = "mailbox" },
    { key = "__GL_GSYNC_ALLOWED",        value = "1" },
    { key = "__GL_VRR_ALLOWED",          value = "1" },
  },
}
