-- hyprtoolkit.lua  –  Waybar theme tokens
-- Generates: hypr/hyprtoolkit.conf
-- hyprtoolkit uses plain key = value lines (no blocks) with 0xAARRGGBB colors.

hl.comment("Colors (Waybar style)")
hl.keyword("background",           "0xCC1E1E2E")
hl.keyword("background_secondary", "0xCC1E1E2E")
hl.raw("")
hl.keyword("text",           "0xE6FFFFFF")
hl.keyword("text_secondary", "0xB3FFFFFF")
hl.raw("")
hl.keyword("accent", "0x59FFFFFF")
hl.raw("")
hl.comment("Borders & rounding")
hl.keyword("border_size",  1)
hl.keyword("border_color", "0x40FFFFFF")
hl.raw("")
hl.keyword("rounding",       12)
hl.keyword("rounding_large", 16)
hl.raw("")
hl.comment("Shadows (soft like Waybar)")
hl.keyword("shadow_size",  20)
hl.keyword("shadow_color", "0x80000000")
hl.raw("")
hl.comment("Blur (IMPORTANT)")
hl.keyword("blur",        true)
hl.keyword("blur_size",   8)
hl.keyword("blur_passes", 2)
hl.raw("")
hl.comment("Padding")
hl.keyword("padding", 10)
