-- gpu/intel.lua  –  Intel GPU environment variables
-- Generates: hypr/env_var/gpu/intel.conf

hl.heading("INTEL GPU OPTIMIZATION")
hl.raw("")
hl.comment("Intel iGPU and Arc GPU support")
hl.comment("Intel Vulkan driver (choose one based on your GPU)")
hl.comment("For older Intel iGPU (UHD/Iris):")
hl.keyword("env", "WLR_RENDERER,vulkan")
hl.keyword("env", "WLR_NO_HARDWARE_CURSORS,1")
hl.keyword("env", "VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/intel_icd.x86_64.json")
hl.comment("For newer Intel Arc GPU:")
hl.raw("# env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/intel_hasvk_icd.x86_64.json")
hl.raw("")
hl.comment("Intel-specific settings")
hl.keyword("env", "INTEL_PRECISE_TRIG,1")
hl.keyword("env", "MESA_LOADER_DRIVER_OVERRIDE,iris")
hl.keyword("env", "INTEL_DEBUG,")
hl.raw("")
hl.comment("VRR/Adaptive Sync (may work on newer Arc)")
hl.keyword("env", "__GL_GSYNC_ALLOWED,1")
hl.keyword("env", "__GL_VRR_ALLOWED,1")
hl.raw("")
hl.comment("Present mode")
hl.keyword("env", "MESA_VK_WSI_PRESENT_MODE,mailbox")
