-- gpu/nvidia.lua  –  NVIDIA GPU environment variables
-- Generates: hypr/env_var/gpu/nvidia.conf

hl.heading("NVIDIA OPTIMIZATION")
hl.raw("")
hl.comment("Wayland + NVIDIA")
hl.keyword("env", "__NV_PRIME_RENDER_OFFLOAD,1")
hl.keyword("env", "__GLX_VENDOR_LIBRARY_NAME,nvidia")
hl.keyword("env", "GBM_BACKEND,nvidia-drm")
hl.keyword("env", "__VK_LAYER_NV_optimus,NVIDIA_only")
hl.raw("")
hl.comment("Vulkan ICD for NVIDIA")
hl.keyword("env", "VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json")
hl.raw("")
hl.comment("NVIDIA-specific settings")
hl.keyword("env", "NVIDIA_MIG_CONFIG,disabled")
hl.keyword("env", "NVIDIA_PRESERVE_VIDEOCORE,1")
hl.raw("")
hl.comment("VRR/Adaptive Sync (NVIDIA G-Sync)")
hl.keyword("env", "__GL_GSYNC_ALLOWED,1")
hl.keyword("env", "__GL_VRR_ALLOWED,1")
hl.raw("")
hl.comment("Wayland rendering")
hl.keyword("env", "WLR_RENDERER,vulkan")
hl.keyword("env", "WLR_NO_HARDWARE_CURSORS,1")
hl.keyword("env", "MESA_VK_WSI_PRESENT_MODE,fifo")
