# General
general {
    grab_focus = true
}

# Cache (tracks frequently used apps!)
cache {
    enabled = true
}

# Finder behavior
finders {
    default_finder = desktop
    desktop_icons = true
    math_prefix = =
}

# UI
ui {
    window_size = 800 400
    anchor = top
    margin_top = 60
}
