# Waybar blur layer rules
layerrule = match:namespace = waybar, blur on
layerrule = match:namespace = waybar, ignore_alpha 0.0
layerrule = match:namespace = waybar, xray off
layerrule = match:namespace = waybar, blur_popups on
