##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps (most users keep this)
windowrule = suppress_event maximize, match:class .*

# Fix dragging/focus issues with certain XWayland floating windows
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:fullscreen 0, match:float 1, match:pin 0

#############################
### WINDOWRULE (GAMING) ###
#############################

# Low-latency fullscreen for games (immediate tearing + no animations)
windowrule = immediate on, match:fullscreen 1
windowrule = no_anim on, match:fullscreen 1