###############################
### AMD / MESA OPTIMIZATION ###
###############################

env = WLR_RENDERER,vulkan
env = WLR_NO_HARDWARE_CURSORS,1

env = RADV_PERFTEST,gpl
env = AMD_VULKAN_ICD,radv

env = VK_ICD_FILENAMES,/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

env = MESA_VK_WSI_PRESENT_MODE,mailbox
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1
