#################################
### GENERIC WAYLAND SETTINGS   ###
#################################

# Generic Vulkan configuration
env = WLR_RENDERER,vulkan
env = WLR_NO_HARDWARE_CURSORS,1

# Generic VRR settings
env = __GL_GSYNC_ALLOWED,1
env = __GL_VRR_ALLOWED,1

# Default present mode
env = MESA_VK_WSI_PRESENT_MODE,mailbox